name: XplorersBot PingOne Library tests

on:
  push:

jobs:
  run_nose_tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install packages
      run: make install

    - name: Test python library with nose tests
      run: make test
